version: '3.7'
services:
    kubeportal:
        image: kubeportal
        container_name: kubeportal
        build:
            context: .
        ports:
            - "8000:8000"
        env_file:
            - .env
