apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeportal
  namespace: kubeportal
  labels:
    app.kubernetes.io/name: kubeportal
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kubeportal
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kubeportal
    spec:
      containers:
      - name: kubeportal
        image: troeger/kubeportal:dev
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: config
        volumeMounts:
        - name: minikube-config
          mountPath: /root/.minikube
        - name: kube-config
          mountPath: /root/.kube

      volumes:
      - name: minikube-config
        projected:
            sources:
                - secret:
                    name: mk-client-crt
                - secret:
                    name: mk-ca-crt
                - secret:
                    name: mk-ca-key
                - secret:
                    name: mk-ca-pem
      - name: kube-config
        secret:
            secretName: kube-config
