apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubeportal-db
  namespace: kubeportal
  labels:
    app.kubernetes.io/name: kubeportal
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
