# Generated by Django 2.2.4 on 2019-12-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubeportal', '0008_user_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kubernetesnamespace',
            name='visible',
        ),
        migrations.AlterField(
            model_name='user',
            name='comments',
            field=models.CharField(blank=True, default='', help_text='Description on why this user needs cluster access. (150 characters)', max_length=150, null=True),
        ),
    ]
